// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: Apache-2.0

export {
  applyChessMove,
  CHESS_START_FEN,
  chessFen,
  chessMoveToUci,
  chessSquare,
  chessSquareName,
  chessStatus,
  type ChessCastlingRights,
  type ChessColor,
  type ChessMove,
  type ChessPiece,
  type ChessPosition,
  type ChessPromotion,
  type ChessStatus,
  isChessCheckmate,
  isChessInCheck,
  isChessSquareAttacked,
  isChessStalemate,
  legalChessMoves,
  parseChessFen,
  parseUciMove,
} from "./chess.ts";
export {
  CHESS_PUZZLE_SELECTION_VERSION,
  type ChessPuzzleAction,
  type ChessPuzzleCatalog,
  type ChessPuzzleDifficulty,
  type ChessPuzzleDirection,
  type ChessPuzzleIssueCode,
  type ChessPuzzleLastMove,
  type ChessPuzzleMode,
  type ChessPuzzlePromotionChooser,
  type ChessPuzzleRecord,
  type ChessPuzzleSelection,
  type ChessPuzzleState,
  type ChessPuzzleStatus,
  type ChessPuzzleTheme,
  chessPuzzleById,
  chessPuzzleExpectedMove,
  chessPuzzleHintText,
  createChessPuzzle,
  createDailyChessPuzzleSelection,
  createPracticeChessPuzzleSelection,
  reduceChessPuzzle,
  selectChessPuzzle,
  submitChessPuzzleMove,
  validateChessPuzzleUtcDate,
} from "./chess-puzzle.ts";
export {
  type ChessPuzzleActivityOptions,
  type ChessPuzzleThemeOption,
  chessPuzzleActivity,
} from "./chess-puzzle-activity.ts";
export {
  CHESS_PUZZLE_MAX_COMPLETIONS,
  CHESS_PUZZLE_STORAGE_SCHEMA_VERSION,
  type ChessPuzzleCompletionRecord,
  type ChessPuzzlePreferences,
  type ChessPuzzleSaveDocument,
  ChessPuzzleSaveError,
  type ChessPuzzleSaveErrorCode,
  type ChessPuzzleSaveWriter,
  type ChessPuzzleStatistics,
  chessPuzzleCompletionKey,
  chessPuzzleSaveJson,
  chessPuzzleStatistics,
  createChessPuzzleSaveWriter,
  createEmptyChessPuzzleSave,
  mergeChessPuzzleCompletions,
  parseChessPuzzleSave,
  updateChessPuzzleSave,
  validateChessPuzzleCatalog,
} from "./chess-puzzle-state.ts";
export {
  CODEWORD_ACCEPTED_GUESSES,
  CODEWORD_ANSWERS,
  CODEWORD_DAILY_SELECTION_VERSION,
  CODEWORD_DICTIONARY_REVISION,
  CODEWORD_LENGTH,
  CODEWORD_MAX_ATTEMPTS,
  CODEWORD_PRACTICE_SELECTION_VERSION,
  type CodewordAction,
  type CodewordDifficulty,
  type CodewordIssue,
  type CodewordScore,
  type CodewordSelection,
  type CodewordState,
  type CodewordStatus,
  type CodewordSubmittedGuess,
  createCodewordGame,
  createDailyCodeword,
  createPracticeCodeword,
  reduceCodeword,
  scoreCodewordGuess,
} from "./codeword.ts";
export { type CodewordActivityOptions, codewordActivity } from "./codeword-activity.ts";
export {
  CODEWORD_STORAGE_SCHEMA_VERSION,
  type CodewordPreferences,
  type CodewordSaveDocument,
  CodewordSaveError,
  type CodewordSaveErrorCode,
  type CodewordStatistics,
  codewordSaveJson,
  codewordStatistics,
  createEmptyCodewordSave,
  EMPTY_CODEWORD_STATISTICS,
  mergeCodewordCompletions,
  parseCodewordSave,
  updateCodewordSave,
} from "./codeword-state.ts";
export {
  createLoungeExtension,
  type LoungeExtensionOptions,
  loungeExtension,
} from "./extension.ts";
export {
  canMove2048,
  createGame2048,
  GAME_2048_ALGORITHM_VERSION,
  GAME_2048_SIZE,
  GAME_2048_TARGET,
  type Game2048Action,
  type Game2048Direction,
  type Game2048Merge,
  type Game2048MoveResult,
  type Game2048MoveTrace,
  type Game2048Snapshot,
  type Game2048Spawn,
  type Game2048State,
  type Game2048Status,
  type Game2048TileMotion,
  moveGame2048,
  reduceGame2048,
  restoreGame2048,
  validateGame2048Snapshot,
} from "./game-2048.ts";
export { type Game2048ActivityOptions, game2048Activity } from "./game-2048-activity.ts";
export {
  GAME_2048_STORAGE_SCHEMA_VERSION,
  type Game2048SaveDocument,
  Game2048SaveError,
  game2048SaveJson,
  parseGame2048Save,
  updateGame2048Save,
} from "./game-2048-state.ts";
export {
  adjacentMineCount,
  createMinesweeper,
  MINESWEEPER_ALGORITHM_VERSION,
  MINESWEEPER_PRESETS,
  type MinesweeperAction,
  type MinesweeperDirection,
  type MinesweeperPreset,
  type MinesweeperPresetDefinition,
  type MinesweeperState,
  type MinesweeperStatus,
  minesweeperCoordinates,
  minesweeperIndex,
  minesweeperNeighbors,
  reduceMinesweeper,
  remainingMineEstimate,
  restoreMinesweeper,
  validateMinesweeperState,
} from "./minesweeper.ts";
export {
  type MinesweeperActivityOptions,
  minesweeperActivity,
} from "./minesweeper-activity.ts";
export {
  MINESWEEPER_STORAGE_SCHEMA_VERSION,
  type MinesweeperSaveDocument,
  MinesweeperSaveError,
  type MinesweeperSaveErrorCode,
  minesweeperSaveJson,
  parseMinesweeperSave,
  updateMinesweeperSave,
} from "./minesweeper-state.ts";
export {
  createSudoku,
  reduceSudoku,
  restoreSudoku,
  selectSudokuFixture,
  SUDOKU_ALGORITHM_VERSION,
  SUDOKU_ALL_NOTES,
  SUDOKU_CELLS,
  SUDOKU_FIXTURES,
  SUDOKU_FIXTURE_SET_REVISION,
  SUDOKU_SELECTION_VERSION,
  SUDOKU_SIZE,
  sudokuConflicts,
  type SudokuAction,
  type SudokuDifficulty,
  type SudokuDirection,
  type SudokuFixture,
  sudokuFixture,
  sudokuGivenValues,
  sudokuPeers,
  sudokuSolution,
  type SudokuSnapshot,
  type SudokuState,
  type SudokuStatus,
  validateSudokuState,
} from "./sudoku.ts";
export { type SudokuActivityOptions, sudokuActivity } from "./sudoku-activity.ts";
export {
  parseSudokuSave,
  SUDOKU_STORAGE_SCHEMA_VERSION,
  type SudokuSaveDocument,
  SudokuSaveError,
  type SudokuSaveErrorCode,
  sudokuSaveJson,
  updateSudokuSave,
} from "./sudoku-state.ts";
