// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: Apache-2.0
// @generated by packages/extensions/lounge/scripts/generate-sudoku-fixtures.ts; do not edit.

export const SUDOKU_FIXTURE_SET_REVISION = "axl-sudoku-v1" as const;

export type SudokuDifficulty = "easy" | "medium" | "hard";

export interface SudokuFixture {
  readonly id: string;
  readonly fixtureSetRevision: typeof SUDOKU_FIXTURE_SET_REVISION;
  readonly difficulty: SudokuDifficulty;
  readonly puzzle: string;
  readonly solution: string;
  readonly clueCount: number;
  readonly rating: {
    readonly nakedSingles: number;
    readonly hiddenSingles: number;
    readonly decisionCount: number;
    readonly maximumDecisionDepth: number;
  };
}

export const SUDOKU_FIXTURES: readonly SudokuFixture[] = Object.freeze([
  Object.freeze({
    id: "easy-01",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "easy",
    puzzle: "472036195105070030830090070701364058900701304364950000583009047600003000000647080",
    solution: "472836195195472836836195472721364958958721364364958721583219647647583219219647583",
    clueCount: 45,
    rating: Object.freeze({
      nakedSingles: 36,
      hiddenSingles: 0,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "easy-02",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "easy",
    puzzle: "087163405061045728950700003036000002720630009005820300540208106002016904013004200",
    solution: "287163495361945728954782613136459872728631549495827361549278136872316954613594287",
    clueCount: 45,
    rating: Object.freeze({
      nakedSingles: 36,
      hiddenSingles: 0,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "easy-03",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "easy",
    puzzle: "069370000031080040285649700508496030946710250103805000000904070010058904690107002",
    solution: "469371825731582649285649713528496137946713258173825496852964371317258964694137582",
    clueCount: 45,
    rating: Object.freeze({
      nakedSingles: 36,
      hiddenSingles: 0,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "easy-04",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "easy",
    puzzle: "602715000100004002090060710071040320048602050320050908480326571015089200063501080",
    solution: "632715894157894632894263715571948326948632157326157948489326571715489263263571489",
    clueCount: 45,
    rating: Object.freeze({
      nakedSingles: 36,
      hiddenSingles: 0,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "medium-01",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "medium",
    puzzle: "000016582000802000050900100004690025196005800002400900900563078005008019827009050",
    solution: "479316582613852794258974136784691325196235847532487961941563278365728419827149653",
    clueCount: 38,
    rating: Object.freeze({
      nakedSingles: 41,
      hiddenSingles: 2,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "medium-02",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "medium",
    puzzle: "201695000074000500600074000000038021430009700000067800910703000003040000042916000",
    solution: "281695473374281596695374182567438921438129765129567834916753248753842619842916357",
    clueCount: 33,
    rating: Object.freeze({
      nakedSingles: 43,
      hiddenSingles: 5,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "medium-03",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "medium",
    puzzle: "642000058300001200150460000204030000000500000000024973080006397006009001970000640",
    solution: "642793158397851264158462739264937815739518426815624973581246397426379581973185642",
    clueCount: 33,
    rating: Object.freeze({
      nakedSingles: 45,
      hiddenSingles: 3,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "medium-04",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "medium",
    puzzle: "000006070005000803020038659010850007700001300000679124050000408840060790079080030",
    solution: "384596271965712843127438659412853967796241385538679124653927418841365792279184536",
    clueCount: 36,
    rating: Object.freeze({
      nakedSingles: 37,
      hiddenSingles: 8,
      decisionCount: 0,
      maximumDecisionDepth: 0,
    }),
  }),
  Object.freeze({
    id: "hard-01",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "hard",
    puzzle: "060300000000200706402000509820060003590080000017003084040007000000900408005000100",
    solution: "761359842359248716482176539824761953593482671617593284248617395176935428935824167",
    clueCount: 28,
    rating: Object.freeze({
      nakedSingles: 47,
      hiddenSingles: 4,
      decisionCount: 2,
      maximumDecisionDepth: 2,
    }),
  }),
  Object.freeze({
    id: "hard-02",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "hard",
    puzzle: "090010000002000500000004096000046031000000200030800000063070920020000800005409000",
    solution: "396715482482693517517284396258946731649137258731852649163578924924361875875429163",
    clueCount: 24,
    rating: Object.freeze({
      nakedSingles: 222,
      hiddenSingles: 42,
      decisionCount: 5,
      maximumDecisionDepth: 3,
    }),
  }),
  Object.freeze({
    id: "hard-03",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "hard",
    puzzle: "000000140000000008900045060000290013006000500003570090680300000020000051001407000",
    solution: "762938145145762938938145762574296813296813574813574296689351427427689351351427689",
    clueCount: 26,
    rating: Object.freeze({
      nakedSingles: 47,
      hiddenSingles: 6,
      decisionCount: 2,
      maximumDecisionDepth: 2,
    }),
  }),
  Object.freeze({
    id: "hard-04",
    fixtureSetRevision: "axl-sudoku-v1",
    difficulty: "hard",
    puzzle: "004003098000420003000091600800002700705000040040000900190004000007008000060500009",
    solution: "624753198981426573573891624819642735735189246246375981198264357357918462462537819",
    clueCount: 26,
    rating: Object.freeze({
      nakedSingles: 56,
      hiddenSingles: 20,
      decisionCount: 1,
      maximumDecisionDepth: 1,
    }),
  }),
]);
