// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: Apache-2.0

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface DictionaryFileRecord {
  readonly path: string;
  readonly count: number;
  readonly sha256: string;
}

interface DictionaryProvenance {
  readonly schemaVersion: number;
  readonly dictionaryRevision: string;
  readonly files: {
    readonly answers: DictionaryFileRecord;
    readonly acceptedGuesses: DictionaryFileRecord;
  };
}

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PROVENANCE_PATH = resolve(PACKAGE_ROOT, "data/codeword/provenance.json");
const TARGET_PATH = resolve(PACKAGE_ROOT, "src/codeword-dictionary.generated.ts");
const CHECK_FLAG = `-${"-"}check`;
const WORD = /^[a-z]{5}$/u;
const CHUNK_WIDTH = 96;

function sha256(source: string): string {
  return createHash("sha256").update(source).digest("hex");
}

function decode(record: DictionaryFileRecord, label: string): readonly string[] {
  const stored = readFileSync(resolve(PACKAGE_ROOT, record.path), "utf8");
  if (!stored.endsWith("\n") || stored.includes("\r") || stored.includes("\n\n")) {
    throw new Error(`${label} front-coded data must use nonempty LF-terminated chunks`);
  }
  const lines = stored.trimEnd().split("\n");
  if (lines.some((line) => line.length > CHUNK_WIDTH || !/^[0-4a-z]+$/u.test(line))) {
    throw new Error(`${label} contains an invalid front-coded chunk`);
  }
  const encoded = lines.join("");
  const words: string[] = [];
  let offset = 0;
  let previous = "";
  while (offset < encoded.length) {
    const prefix = Number(encoded[offset]);
    if (!Number.isInteger(prefix) || prefix < 0 || prefix > 4 || prefix > previous.length) {
      throw new Error(`${label} contains an invalid prefix length at byte ${offset}`);
    }
    offset += 1;
    const suffixLength = 5 - prefix;
    const suffix = encoded.slice(offset, offset + suffixLength);
    if (suffix.length !== suffixLength || !/^[a-z]+$/u.test(suffix)) {
      throw new Error(`${label} contains an invalid suffix at byte ${offset}`);
    }
    offset += suffixLength;
    const word = previous.slice(0, prefix) + suffix;
    if (!WORD.test(word) || (previous !== "" && previous >= word)) {
      throw new Error(`${label} must decode to sorted unique five-letter words`);
    }
    words.push(word);
    previous = word;
  }
  if (words.length !== record.count) throw new Error(`${label} count does not match`);
  const source = `${words.join("\n")}\n`;
  if (sha256(source) !== record.sha256) throw new Error(`${label} checksum does not match`);
  return words;
}

function renderChunks(record: DictionaryFileRecord): string {
  const stored = readFileSync(resolve(PACKAGE_ROOT, record.path), "utf8");
  return stored
    .trimEnd()
    .split("\n")
    .map((chunk) => `  ${JSON.stringify(chunk)},`)
    .join("\n");
}

function generatedSource(): string {
  const provenanceText = readFileSync(PROVENANCE_PATH, "utf8");
  const provenance = JSON.parse(provenanceText) as DictionaryProvenance;
  if (`${JSON.stringify(provenance, null, 2)}\n` !== provenanceText) {
    throw new Error("Codeword provenance must be canonical JSON");
  }
  if (provenance.schemaVersion !== 1) throw new Error("Unsupported provenance schema version");
  if (!/^esdb-\d{4}\.\d{2}\.\d{2}-axl-codeword-v\d+$/u.test(provenance.dictionaryRevision)) {
    throw new Error("Invalid Codeword dictionary revision");
  }
  const answers = decode(provenance.files.answers, "Codeword answers");
  const accepted = decode(provenance.files.acceptedGuesses, "Codeword accepted guesses");
  const acceptedSet = new Set(accepted);
  for (const answer of answers) {
    if (!acceptedSet.has(answer)) throw new Error(`Codeword answer ${answer} is not accepted`);
  }

  return `// SPDX-FileCopyrightText: 2000-2026 Kevin Atkinson
// SPDX-FileCopyrightText: 2026 Kaushik Kumar
// SPDX-License-Identifier: LicenseRef-ESDB
// @generated by packages/extensions/lounge/scripts/generate-codeword-dictionary.ts; do not edit.

const WORD_LENGTH = 5;

function decodeFrontCoded(chunks: readonly string[], expectedCount: number): readonly string[] {
  const encoded = chunks.join("");
  const words: string[] = [];
  let offset = 0;
  let previous = "";
  while (offset < encoded.length) {
    const prefix = Number(encoded[offset]);
    if (
      !Number.isInteger(prefix) ||
      prefix < 0 ||
      prefix >= WORD_LENGTH ||
      prefix > previous.length
    ) {
      throw new Error("Invalid generated Codeword dictionary prefix");
    }
    offset += 1;
    const suffixLength = WORD_LENGTH - prefix;
    const suffix = encoded.slice(offset, offset + suffixLength);
    if (suffix.length !== suffixLength || !/^[a-z]+$/u.test(suffix)) {
      throw new Error("Invalid generated Codeword dictionary suffix");
    }
    offset += suffixLength;
    const word = previous.slice(0, prefix) + suffix;
    if (previous !== "" && previous >= word) {
      throw new Error("Generated Codeword dictionary is not strictly sorted");
    }
    words.push(word);
    previous = word;
  }
  if (words.length !== expectedCount)
    throw new Error("Generated Codeword dictionary count mismatch");
  return Object.freeze(words);
}

export const CODEWORD_DICTIONARY_REVISION = ${JSON.stringify(provenance.dictionaryRevision)} as const;

const ANSWER_CHUNKS = [
${renderChunks(provenance.files.answers)}
] as const;

const ACCEPTED_GUESS_CHUNKS = [
${renderChunks(provenance.files.acceptedGuesses)}
] as const;

export const CODEWORD_ANSWERS = decodeFrontCoded(ANSWER_CHUNKS, ${answers.length});
export const CODEWORD_ACCEPTED_GUESSES = decodeFrontCoded(ACCEPTED_GUESS_CHUNKS, ${accepted.length});
`;
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : "";
if (invokedPath === fileURLToPath(import.meta.url)) {
  const source = generatedSource();
  if (process.argv[2] === CHECK_FLAG) {
    const target = resolve(process.cwd(), process.argv[3] ?? TARGET_PATH);
    if (target !== TARGET_PATH) {
      throw new Error(
        `No Codeword dictionary output exists for ${relative(process.cwd(), target)}`,
      );
    }
    if (readFileSync(target, "utf8") !== source) process.exitCode = 1;
  } else {
    writeFileSync(TARGET_PATH, source);
  }
}
