// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-FileCopyrightText: 2026 Lokesh
// SPDX-License-Identifier: Apache-2.0

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type GeneratorRunner = (
  file: string,
  arguments_: string[],
  options: { cwd: string; stdio: "pipe" },
) => unknown;

function walk(directory: string, visit: (path: string) => void): void {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if ([".git", "_build", "deps", "dist", "node_modules"].includes(entry.name)) continue;
    if (entry.isSymbolicLink()) continue;
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) walk(path, visit);
    else visit(path);
  }
}

export function checkGenerated(root: string, run: GeneratorRunner = execFileSync): string[] {
  const errors: string[] = [];
  walk(root, (path) => {
    const source = readFileSync(path, "utf8");
    const marker = source
      .split("\n", 5)
      .join("\n")
      .match(/@generated by ([^;]+); do not edit\./);
    const namedGenerated = /\.generated\.[^.]+$/.test(path);
    if (!marker && !namedGenerated) return;
    const generatorPath = marker?.[1];
    if (!generatorPath) {
      errors.push(`${relative(root, path)} is generated but has no generator marker`);
      return;
    }
    if (!generatorPath.endsWith(".ts")) {
      errors.push(`${relative(root, path)} must name a TypeScript generator`);
      return;
    }

    const generator = resolve(root, generatorPath);
    if (!existsSync(generator)) {
      errors.push(`${relative(root, path)} names missing generator ${generatorPath}`);
      return;
    }

    try {
      run(process.execPath, [generator, "--check", relative(root, path)], {
        cwd: root,
        stdio: "pipe",
      });
    } catch {
      errors.push(`${relative(root, path)} differs from its generator output`);
    }
  });
  return errors;
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : "";
if (invokedPath === fileURLToPath(import.meta.url)) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const errors = checkGenerated(root);
  if (errors.length > 0) {
    console.error(errors.join("\n"));
    process.exitCode = 1;
  } else {
    console.log("Generated files match their generators.");
  }
}
