// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-FileCopyrightText: 2026 Lokesh
// SPDX-License-Identifier: Apache-2.0

import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { checkGenerated } from "./check-generated.ts";

test("requires generated files to name an existing passing generator", () => {
  const root = mkdtempSync(join(tmpdir(), "axl-generated-"));
  const output = join(root, "schema.generated.ts");
  writeFileSync(output, "// generated without a marker\n");
  assert.equal(checkGenerated(root).length, 1);

  writeFileSync(output, "// @generated by generate.ts; do not edit.\n");
  assert.equal(checkGenerated(root).length, 1);

  writeFileSync(join(root, "generate.ts"), "");
  assert.deepEqual(
    checkGenerated(root, () => undefined),
    [],
  );
});

test("ignores dependency builds and directory symlinks", () => {
  const root = mkdtempSync(join(tmpdir(), "axl-generated-builds-"));
  mkdirSync(join(root, "deps"));
  mkdirSync(join(root, "_build"));
  writeFileSync(join(root, "deps", "ignored.generated.ts"), "");
  writeFileSync(join(root, "_build", "ignored.generated.ts"), "");
  symlinkSync(join(root, "deps"), join(root, "linked-deps"));

  assert.deepEqual(checkGenerated(root), []);
});
